### ISSUE TITLE
SapColCmdLn error

### ISSUE THREAD

**Issue by mjlaws** [ExCiteS/Sapelli#115]
I am having trouble uploading Sapelli projects to GeoKey.

The error message is as follows:

Failed to load Sapelli project, due to:

SapColCmdLn error

×Close Java stacktrace:
java.lang.Exception: Error on extracting contents of Sapelli file.
    at uk.ac.ucl.excites.sapelli.collector.load.ProjectLoader.load(ProjectLoader.java:244)
    at uk.ac.ucl.excites.sapelli.collector.load.ProjectLoader.load(ProjectLoader.java:214)
    at uk.ac.ucl.excites.sapelli.collector.SapColCmdLn.main(SapColCmdLn.java:111)
Caused by: java.io.FileNotFoundException: /var/www/media/sapelli/1334_megan-laws/Temp/1553016498068/img/approve.png (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
    at uk.ac.ucl.excites.sapelli.shared.io.Unzipper.unzip(Unzipper.java:67)
    at uk.ac.ucl.excites.sapelli.collector.load.ProjectLoader.load(ProjectLoader.java:239)
    ... 2 more

**Comment by vbonnal** [comment]
I have the same error with this file...
[Fogo v1.0.sap](https://nubes.teledetection.fr/index.php/s/KrNGy5j6XBaXX57/download/Fogo%20v1.0.sap)
