### ISSUE TITLE
CSVRecordsExporter.java line 111

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#33]
#### in uk.ac.ucl.excites.sapelli.storage.eximport.csv.CSVRecordsExporter.<init>

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/560d2cb9f5d3a7f76b7854f8](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/560d2cb9f5d3a7f76b7854f8)

**Comment by mstevens83** [comment]
**BUILD_INFO**
*Built by mstevens on 2014-08-21 15:32:41 BST using master branch, revision 8f32c1d with changes

````
java.lang.IllegalArgumentException: Export folder (/mnt/sdcard/Sapelli/Export) does not exist and could not be created!
       at uk.ac.ucl.excites.sapelli.storage.eximport.csv.CSVRecordsExporter.<init>(CSVRecordsExporter.java:111)
       at uk.ac.ucl.excites.sapelli.collector.activities.ExportActivity.queryCallback(ExportActivity.java:282)
       at uk.ac.ucl.excites.sapelli.collector.activities.ExportActivity.access$300(ExportActivity.java:69)
       at uk.ac.ucl.excites.sapelli.collector.activities.ExportActivity$QueryTask.onPostExecute(ExportActivity.java:404)
       at uk.ac.ucl.excites.sapelli.collector.activities.ExportActivity$QueryTask.onPostExecute(ExportActivity.java:361)
       at android.os.AsyncTask.finish(AsyncTask.java:417)
       at android.os.AsyncTask.access$300(AsyncTask.java:127)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3687)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
       at dalvik.system.NativeStart.main(NativeStart.java)
````

**Comment by mstevens83** [comment]
**SAPELLI_DEVICE_ID_CRC32**
*4136949986* (= Xcover1)

Same device as in issues #30 and #32.
